filter seize options by active expansions
dennishorte/battlestar pull request #4
Opened 2023-12-30 22:25 UTC by cpapazian

according to the rules, if the expansion that a relic "belongs" to is not in play, you may not seize that relic to your hand (only achievements, or not at all). this commit introduces a `relicExpansion` field on the card, and checks that against the set of active expansions before the seize prompt is displayed so that the rules are properly enforced.

2023-12-30 22:26 UTC, cpapazian commented
<img width="389" alt="image" src="https://github.com/dennishorte/battlestar/assets/1939552/738fb36f-4fe0-4e90-baf3-8fe8abce846f">

2023-12-30 22:31 UTC, cpapazian commented on common/innovation/res/arti/achievements/ComplexNumbers.js
> +  this.relicExpansion = 'base'
wasn't sure of this

2023-12-30 22:31 UTC, cpapazian commented on common/innovation/res/arti/achievements/NewtonWickinsTelescope.js
> +  this.relicExpansion = 'arti'
or this

2023-12-30 22:49 UTC, dennishorte requested changes
There is a debug log statement that needs to be removed.

2023-12-30 22:49 UTC, dennishorte commented on common/innovation/innovation.js
> +  console.log(card, this.getExpansionList(), this.getExpansionList().includes(card.relicExpansion))
Need to remove this log statement.

2023-12-30 22:54 UTC, cpapazian commented on common/innovation/innovation.js
> +  console.log(card, this.getExpansionList(), this.getExpansionList().includes(card.relicExpansion))
fixe

2023-12-30 22:54 UTC, cpapazian commented on common/innovation/innovation.js
> +  console.log(card, this.getExpansionList(), this.getExpansionList().includes(card.relicExpansion))
d

2023-12-31 17:47 UTC, dennishorte approved these changes

2023-12-31 17:47 UTC, merged